BoXueGu/BoXueGu/apps/contents/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(),name='index'),
    url(r'^userinfo',views.UserInfoView.as_view(),name='user_info'),
]

BoXueGu/BoXueGu/apps/courses/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url('^courseslist/$',views.CourseListView.as_view(),name='course_list'),
]

BoXueGu/BoXueGu/apps/organization/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url('^orglist',views.OrgListView.as_view(),name='org_list'),
    url('^orgteacher',views.TeacherListView.as_view(),name='teacher_list'),
    url('^add_fav',views.AddfavView.as_view(),name='add_fav'),
]

BoXueGu/BoXueGu/apps/users/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^register/$', views.RegisterView.as_view(), name='register'),
    url(r'^forget/$', views.ForgetPwdView.as_view(), name='forget_pwd'),
    url(r'^user_info/$', views.UserInfoView.as_view(), name='user_info'),
    url(r'^mymessage/$', views.Mymessage.as_view(), name='mymessage'),
    url(r'^mycourse/$', views.Mycourse.as_view(), name='mycourse'),
    url(r'^myfav_org/$', views.Myfav_org.as_view(), name='myfav_org'),
    url(r'^image_upload/$', views.Image_upload.as_view(), name='image_upload'),
    url(r'^reset/(?P<active_code>.*)/$', views.ResetView.as_view(), name='reset_pwd'),
    url(r'^modify_pwd/$',views.ModifyPwdView.as_view(),name='modify_pwd'),
]

BoXueGu/BoXueGu/urls.py
import xadmin
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'xadmin/',xadmin.site.urls),
    url(r'^',include('users.urls',namespace='users')),
    url(r'^',include('organization.urls',namespace='org')),
    url(r'^',include('operation.urls')),
    url(r'^',include('courses.urls',namespace='courses')),
    url(r'^',include('contents.urls',namespace='contents')),
    # 图片验证码路由
    url(r'^captcha/', include('captcha.urls')),
]

BoXueGu/BoXueGu/apps/courses/models.py
from datetime import datetime

from django.db import models

from organization.models import CourseOrg, Teacher
# Create your models here.


class Course(models.Model):
    """课程信息表"""
    course_org = models.ForeignKey(CourseOrg, verbose_name='课程学校', null=True, blank=True)
    name = models.CharField(max_length=52, verbose_name='课程名字')
    desc =  models.CharField(max_length=300, verbose_name='课程描述')
    teacher = models.ForeignKey(Teacher, verbose_name='讲师', null=True, blank=True)
    detail = models.TextField(verbose_name='课程详情')
    degree = models.CharField(choices=(('cj', '初级'), ('zj', '中级'), ('gj', '高级')), max_length=2, verbose_name='难度')
    # 使用分钟做后台记录(存储最小单位)前台转换
    learn_times = models.IntegerField(default=0, verbose_name='学习时长(分钟数)')
    # 保存学习人数:点击开始学习才算
    students = models.IntegerField(default=0, verbose_name='学习人数')
    fav_nums = models.IntegerField(default=0, verbose_name='收藏人数')
    image = models.ImageField(upload_to='courses/%Y/%m', verbose_name='封面图', max_length=100)
    click_nums = models.IntegerField(default=0, verbose_name='点击数')
    is_banner = models.BooleanField(default=False, verbose_name=u'是否是轮播图')
    category = models.CharField(default='后端', max_length=20, verbose_name='课程类别')
    tag = models.CharField(default='', verbose_name='课程标签', max_length=10)
    youneed_konw = models.CharField(default='', max_length=300, verbose_name='课前须知')
    teacher_tell = models.CharField(default='', max_length=300, verbose_name='老师告诉你能学什么')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta:
        verbose_name = '课程'
        verbose_name_plural = verbose_name

    def get_zj_nums(self):
        # 获取课程章节数的方法
        return self.lesson_set.all().count()

    def get_learn_users(self):
        # 获取学习这门课程的用户
        return self.usercourse_set.all()[:5]

    def get_course_lesson(self):
        return self.lesson_set.all()

    def __str__(self):
        return self.name


class BannerCourse(Course):
    class Meta:
        verbose_name = u'轮播课程'
        verbose_name_plural = verbose_name
        # 如果不设置 proxy ，就会再生成一个 BannerCourse 数据表
        proxy = True


# 章节信息
class Lesson(models.Model):
    """章节模型"""
    # 因为一个课程对应很多章节。所以在章节表中将课程设置为外键。
    # 作为一个字段来让我们可以知道这个章节对应那个课程
    course = models.ForeignKey(Course, verbose_name='课程')
    name = models.CharField(max_length=100, verbose_name='章节名')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta:
        verbose_name = '章节'
        verbose_name_plural = verbose_name

    def get_lesson_video(self):
        return self.video_set.all()

    def __str__(self):
        return self.name


class Video(models.Model):
    """每章视频"""
    # 因为一个章节对应很多视频。所以在视频表中将章节设置为外键。
    # 作为一个字段来存储让我们可以知道这个视频对应哪个章节.
    lesson = models.ForeignKey(Lesson, verbose_name='章节')
    name = models.CharField(max_length=100, verbose_name='视频名')
    url = models.URLField(max_length=200, verbose_name='访问地址', default='www.baidu.com')
    # 使用分钟做后台记录(存储最小单位)前台转换
    learn_times = models.IntegerField(default=0, verbose_name='视频时长(分钟数)')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta:
        verbose_name = '视频'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class CourseResource(models.Model):
    """课程资源"""
    # 因为一个课程对应很多资源。所以在课程资源表中将课程设置为外键。
    # 作为一个字段来让我们可以知道这个资源对应那个课程
    course = models.ForeignKey(Course, verbose_name='课程')
    name = models.CharField(max_length=100, verbose_name='课件名')
    download = models.FileField(upload_to='course/resource/%Y/%m', verbose_name='资源文件', max_length=100)
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta:
        verbose_name = u'课程资源'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

BoXueGu/BoXueGu/apps/operation/models.py
from datetime import datetime

from django.db import models

# Create your models here.

from users.models import UserProfile
from courses.models import Course

class UserAsk(models.Model):
    """用户我要学习表单"""
    name = models.CharField(max_length=20, verbose_name='姓名')
    mobile = models.CharField(max_length=11, verbose_name='手机')
    course_name = models.CharField(max_length=50, verbose_name='课程名')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta:
        verbose_name = '用户咨询'
        verbose_name_plural = verbose_name


class CourseComments(models.Model):
    """用户对于课程评论"""
    user = models.ForeignKey(UserProfile, verbose_name='用户')
    course = models.ForeignKey(Course, verbose_name='课程')
    comments = models.CharField(max_length=200, verbose_name='评论')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta:
        verbose_name = '课程评论'
        verbose_name_plural = verbose_name


class UserFavorite(models.Model):
    """用户对于课程,学校，讲师的收藏"""
    user = models.ForeignKey(UserProfile, verbose_name='用户')
    # ID 是课程的或者是 讲师、课程学校的 ID
    fav_id = models.IntegerField(default=0, verbose_name='收藏数据 Id')
    fav_type = models.IntegerField(choices=( (1, '课程'), (2, '课程学校'), (3, '讲师') ), default=1, verbose_name='收藏类型')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta:
        verbose_name = '用户收藏'
        verbose_name_plural = verbose_name

    # 初始化判断是否收藏
    # has_fav = False
    # if request.user.is_authenticated():
    #     if UserProfile.objects.filter(user=request.user, fav_id=course_org.id, fav_type=2):
    #         has_fav = True


class UserMessage(models.Model):
    """用户消息表"""

    # 如果 为 0 代表全局消息，否则就是用户的 ID
    user = models.IntegerField(default=0, verbose_name='接受用户')
    message = models.CharField(max_length=500, verbose_name='消息内容')
    has_read = models.BooleanField(default=False, verbose_name='是否已读')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta:
        verbose_name = '用户消息'
        verbose_name_plural = verbose_name


# CourseComments 和 UserCourse 字段差不多，可以使用 UserCourse 继承 CourseComments
class UserCourse(models.Model):
    """用户课程表"""
    user = models.ForeignKey(UserProfile, verbose_name='用户')
    course = models.ForeignKey(Course, verbose_name='课程')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta:
        verbose_name = '用户学习过的课程'
        verbose_name_plural = verbose_name

BoXueGu/BoXueGu/apps/organization/models.py
from datetime import  datetime

from django.db import models

# Create your models here.


class CityDict(models.Model):
    """城市字典"""
    name = models.CharField(max_length=20, verbose_name='城市')
    # 城市描述：备用不一定展示出来
    desc = models.TextField(verbose_name='城市描述')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta:
        verbose_name = '城市'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class CourseOrg(models.Model):
    """课程学校"""
    name = models.CharField(max_length=50, verbose_name='学校名称')
    # 学校类别:
    category = models.CharField(max_length=20, choices=( ('pxjg', '培训学校'), ('gr', '个人'), ('gx', '高校') ), default='pxjg', verbose_name='学校类别' )
    # 学校描述，后面会替换为富文本展示
    desc = models.TextField(verbose_name='学校描述')
    tag = models.CharField(default=u'全国知名', max_length=10, verbose_name=u'学校标签')
    click_nums = models.IntegerField(default=0, verbose_name='点击数')
    fav_nums = models.IntegerField(default=0, verbose_name='收藏数')
    image = models.ImageField(default='', upload_to='org/%Y/%m', verbose_name='封面图', max_length=100)
    address = models.CharField(max_length=150, verbose_name='学校地址')
    # 一个城市可以有很多课程学校，通过将city设置外键，变成课程学校的一个字段
    # 可以让我们通过学校找到城市
    city = models.ForeignKey(CityDict, verbose_name='所在城市')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')
    students = models.IntegerField(default=0, verbose_name='学习人数')

    class Meta:
        verbose_name = '课程学校'
        verbose_name_plural = verbose_name

    def get_teacher_nums(self):
        return self.teacher_set.all().count()

    def course_nums(self):
        return self.course_set.all().count()

    def __str__(self):
        return self.name


class Teacher(models.Model):
    """讲师"""
    # 一个学校会有很多老师，所以我们在讲师表添加外键并把课程学校名称保存下来
    # 可以使我们通过讲师找到对应的学校
    org = models.ForeignKey(CourseOrg, verbose_name='所属学校')
    name = models.CharField(max_length=50, verbose_name='教师名字')
    work_years = models.IntegerField(default=0, verbose_name='工作年限')
    work_company = models.CharField(max_length=50, verbose_name='就职公司')
    work_position = models.CharField(max_length=50, verbose_name='公司职位')
    points = models.CharField(max_length=50, verbose_name='教学特点')
    click_nums = models.IntegerField(default=0, verbose_name='点击数')
    fav_nums = models.IntegerField(default=0, verbose_name='收藏数')
    age = models.IntegerField(default=30, verbose_name='年龄')
    image = models.ImageField(default='', upload_to='teacher/%Y/%m', verbose_name='头像', max_length=100)
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta:
        verbose_name = '教师'
        verbose_name_plural = verbose_name

    def get_course_nums(self):
        return self.course_set.all().count()

    def __str__(self):
        return self.name

BoXueGu/BoXueGu/apps/users/models.py
from datetime import datetime

from django.db import models

from django.contrib.auth.models import AbstractUser
# Create your models here.


class UserProfile(AbstractUser):
    # 用户信息
    # 昵称
    nick_name = models.CharField(max_length=50, verbose_name='昵称', default='')
    # 生日，可以为空
    birthday = models.DateField(null=True, blank=True, verbose_name='生日')
    # 性别 只能男或女，默认女
    gender = models.CharField(max_length=6, choices=(('male', '男'), ('female', '女')), default='female', verbose_name='性别')
    # 地址
    address = models.CharField(max_length=100, default='', verbose_name='地址')
    # 电话
    mobile = models.CharField(max_length=11, null=True, blank=True, verbose_name='手机号')
    #  头像 默认使用default.png
    image = models.ImageField(max_length=100, upload_to='image/%Y/%m', default='image?default.png', verbose_name='头像')

    class Meta:
        verbose_name = '用户信息'
        verbose_name_plural = verbose_name

    def get_unread_nums(self):
        # 获取用户未读数据数量
        from operation.models import UserMessage
        return UserMessage.objects.filter(user=self.id, has_read=False).count()

    def __str__(self):
        return self.username


class EmailVerifyRecord(models.Model):
    """邮箱验证码model"""
    code = models.CharField(max_length=20, verbose_name='验证码')
    email = models.EmailField(max_length=50, verbose_name='邮箱')
    send_type = models.CharField(max_length=18, choices=(('register', '邮箱'), ('forget', '修改密码'), ('update_email', '修改邮箱')),
                                 verbose_name='验证码类型')
    send_time = models.DateField(default=datetime.now, verbose_name='发送时间')

    class Meta:
        verbose_name = '邮箱验证码'
        verbose_name_plural = '邮箱验证码'


class Banner(models.Model):
    """轮播图模型类"""
    title = models.CharField(max_length=100, verbose_name='标题')
    image = models.ImageField(upload_to='banner/%Y/%m', max_length=100, verbose_name='轮播图')
    url = models.URLField(max_length=200, verbose_name='访问地址')
    index = models.IntegerField(default=100, verbose_name='顺序')
    add_time = models.DateField(default=datetime.now, verbose_name='添加时间')

    class Meta:
        verbose_name = '轮播图'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title

BoXueGu/BoXueGu/apps/users/forms.py
from captcha.fields import CaptchaField
from django import forms
from django.core import validators

from users.models import UserProfile


class RegisterForm(forms.Form):
    """
        用户注册表单
    """
    # email = forms.EmailField(max_length=30,min_length=6,required=True,label='用户名',error_messages={'required': "邮箱不能为空"})
    # password = forms.CharField(max_length=20, min_length=8, required=True,label='密码',error_messages={'required': "密码不能为空"})
    # mobile = forms.CharField(max_length=11, min_length=11,required=True,label='手机号',error_messages={'required':'手机号不能为空'})
    email = forms.CharField(validators=[
        validators.RegexValidator("^[0-9a-zA-Z_]{0,19}@[0-9a-zA-Z]{1,13}\.[com,cn,net]{1,3}$", message='请输入正确的邮箱格式！')],
                            required=True, error_messages={'required': "邮箱不能为空"})
    password = forms.CharField(validators=[
        validators.RegexValidator("^[0-9a-zA-Z_]{6,20}$", message='密码为6-20位，且不能有特殊字符！')], required=True, label='密码',
                               error_messages={'required': "密码不能为空"})
    nickname = forms.CharField(max_length=10, min_length=4, required=True, label='昵称',
                               error_messages={'required': "昵称不能为空"})
    mobile = forms.CharField(validators=[validators.RegexValidator("1[345678]\d{9}", message='请输入正确格式的手机号码！')],
                             required=True, error_messages={'required': "手机号码不能为空"})

    # 增加验证码字段
    captcha = CaptchaField(label='验证码', error_messages={'invalid': "验证码不正确"})


class LoginForm(forms.Form):
    """
        用户登录表单
    """
    username = forms.CharField(max_length=30, min_length=6, required=True, error_messages={'required': "账号不能为空"})
    password = forms.CharField(max_length=20, min_length=8, widget=forms.PasswordInput, required=True,
                               error_messages={'required': "密码不能为空"})

class ForgetForm(forms.Form):
    """
        忘记密码表单
    """
    email = forms.EmailField(max_length=30, min_length=6, required=True, error_messages={'required': "账号不能为空"})
    captcha = CaptchaField(label='验证码', error_messages={'invalid': "验证码不正确"})

class ModifyForm(forms.Form):
    """
        修改密码表单
    """
    password1 = forms.CharField(validators=[
        validators.RegexValidator("^[0-9a-zA-Z_]{6,20}$", message='密码为6-20位，且不能有特殊字符！')], required=True, label='密码',
                               error_messages={'required': "密码不能为空"})
    password2 = forms.CharField(required=True, label='密码',error_messages={'required': "密码不能为空"})
    email = forms.CharField(validators=[
        validators.RegexValidator("^[0-9a-zA-Z_]{0,19}@[0-9a-zA-Z]{1,13}\.[com,cn,net]{1,3}$", message='请输入正确的邮箱格式！')],
        required=True, error_messages={'required': "邮箱不能为空"})
    # captcha = CaptchaField(label='验证码', error_messages={'invalid': "验证码不正确"})

BoXueGu/BoXueGu/apps/contents/views.py
from django.shortcuts import render
from django.views import View

from courses.models import Course, BannerCourse
from organization.models import CourseOrg
from users.models import Banner

class IndexView(View):
    def get(self, request):
        all_banners = Banner.objects.all()
        courses = Course.objects.all()
        banner_courses = BannerCourse.objects.all()
        course_orgs = CourseOrg.objects.all()

        content = {
            'all_banners': all_banners,
            'courses': courses,
            'banner_courses': banner_courses,
            'course_orgs': course_orgs,
        }
        return render(request, 'index.html',content)


class UserInfoView(View):
    pass

BoXueGu/BoXueGu/apps/courses/views.py
from django.shortcuts import render
from django.views import View


class CourseListView(View):
    pass

BoXueGu/BoXueGu/apps/operation/views.py
from django.shortcuts import render

# Create your views here.

BoXueGu/BoXueGu/apps/organization/views.py
from django.shortcuts import render
from django.views import View


class OrgListView(View):
    pass

class TeacherListView(View):
    pass

class AddfavView(View):
    pass

BoXueGu/BoXueGu/templates/active_fail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>错误</title>
</head>
<body>
<h1>链接失效</h1>
</body>
</html>

BoXueGu/BoXueGu/templates/base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
  <meta charset="UTF-8">
  <meta name="renderer" content="webkit">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <title>{% block title %}学校课程列表 - 博学谷在线网{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'css/reset.css' %}">
  <link rel="stylesheet" href="{% static 'css/animate.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block custom_css %}{% endblock %}
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}"></script>

</head>
<body>
<section class="headerwrap ">
  <header>
    <div class=" header">
      <div class="top">
        <div class="wp">
          <div class="fl"><p>服务电话：<b>010-56288220</b></p></div>
          <!--登录后跳转-->
          {% if request.user.is_authenticated %}
            <div class="personal">
              <dl class="user fr">
                <dd>{{ request.user.nick_name }}<img class="down fr" src="{% static 'images/top_down.png' %}"/></dd>
                <dt><img width="20" height="20" src="/static{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
              </dl>
              <div class="userdetail">
                <dl>
                  <dt><img width="80" height="80" src="/static{{ MEDIA_URL }}{{ request.user.image }}" /></dt>
                  <dd>
                    <h2>{{ request.user.nick_name }}</h2>
                    <p>{{ request.user.username }}</p>
                  </dd>
                </dl>
                <div class="btn">
                  <a class="personcenter fl" href="{% url 'users:user_info' %}">进入个人中心</a>
                  <a class="fr" href="{% url 'users:logout' %}">退出</a>
                </div>
              </div>
            </div>
            <a href="">
              <div class="msg-num">
                <span id="MsgNum">{{ request.user.unread_nums }}</span>
              </div>
            </a>
          {% else %}
            <a style="color:white" class="fr registerbtn" href="{% url 'users:register' %}">注册</a>
            <a style="color:white" class="fr loginbtn" href="{% url 'users:login' %}">登录</a>
          {% endif %}
        </div>
      </div>

      <div class="middle">
        <div class="wp">
          <a href="{% url 'contents:index' %}" ><img class="fl" src="{% static 'images/logo.jpg' %}" id="boxue" width="140px" height="60px"/></a>
          <div class="searchbox fr">
            <div class="selectContainer fl">
                            <span class="selectOption" id="jsSelectOption" data-value="course">
                                公开课
                            </span>
              <ul class="selectMenu" id="jsSelectMenu">
                <li data-value="course">公开课</li>
                <a href="{% url 'org:org_list' %}"><li data-value="org">学校课程</li></a>
                <li data-value="teacher">授课老师</li>
              </ul>
            </div>
            <input id="search_keywords" class="fl" type="text" value="" placeholder="请输入搜索内容"/>
            <img class="search_btn fr" id="jsSearchBtn" src="{% static 'images/search_btn.png' %}"/>
          </div>
        </div>
      </div>


      <nav>
        <div class="nav">
          <div class="wp">
            <ul>
              <li class="{% ifequal request.path '/' %}active{% endifequal %}"><a href="{% url 'contents:index' %}">首页</a></li>
              <li class="{% ifequal request.path|slice:'7' '/course' %}active{% endifequal %}">
                <a href="{% url 'courses:course_list' %}">
                  公开课<img class="hot" src="{% static 'images/nav_hot.png' %}">
                </a>
              </li>
              <li class="{% ifequal request.path|slice:'12' '/org/teacher' %}active{% endifequal %}">
                <a href="{% url 'org:teacher_list' %}">授课教师</a>
              </li>
              <li class="{% ifequal request.path|slice:'9' '/org/list' %}active{% endifequal %}"><a href="{% url 'org:org_list' %}">授课学校</a></li>
            </ul>
          </div>
        </div>
      </nav>

    </div>
  </header>
</section>
<!--crumbs start-->

<!--  面包屑 -->
{% block custom_bread %}
<section>
  <div class="wp">
    <ul class="crumbs">
      <li><a href="{% url 'index' %}">首页</a>></li>
      <li>学校课程</li>
    </ul>
  </div>
</section>
{% endblock %}

<!-- 页面 body 内容 -->
{% block custom_content %}
{% endblock %}

<!-- Footer -->
<footer>
  <div class="footer">
    <div class="wp">
      <ul class="cont">
        <li class="logo"><a href=""><img src="{% static 'images/footlogo.png' %}"/></a></li>
        <li class="code"><img src="{% static 'images/code.png' %}"/>
          <p class="center">扫描关注微信</p></li>
        <li class="third"><img class="fl" src="{% static 'images/tell.png' %}"/>
          <p class="tell">010-56288220</p>
          <p class="time">周一至周日 9:00-18:00</p></li>
      </ul>

    </div>
    <p class="line"></p>
    <div class="wp clear">
      <span class="fl"> 2016 https://www.boxuegu.com/ 博学谷在线-在线学习交流平台 保留所有权利</span>
      <span class="fr">copyright ? 2016 ICP备案证书号：蜀ICP备xxxxx号-1</span>
    </div>
  </div>
</footer>

<section>
  <ul class="sidebar">
    <li class="qq">
      <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
    </li>
    <li class="totop"></li>
  </ul>
</section>
<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script src="{% static 'js/deco-common.js' %}" type='text/javascript'></script>
<script src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}"></script>
<script src="{% static 'js/unslider.js' %}"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js'  %}"></script>
<script src="{% static 'js/deco-common.js' %}"></script>

{% block custom_js %}{% endblock %}
</body>
</html>

BoXueGu/BoXueGu/templates/org-detail-desc.html
{% extends 'org-base.html' %}
{% load staticfiles %}
{% block custom_title %}课程学校介绍{% endblock %}
{% block page_path %}课程学校介绍{% endblock %}
{% block right_form %}
<div class="right companycenter layout">
  <div class="head">
    <h1>学校介绍</h1>
  </div>
  <p class="des">{{ course_org.desc }}</p>
</div>
{% endblock %}

BoXueGu/BoXueGu/templates/usercenter-fav-teacher.html
{% extends 'usercenter-base.html' %}
{% load staticfiles %}
{% block title %}我的课程-博学谷在线网{% endblock %}

{% block custom_bread %}
<section>
  <div class="wp">
    <ul class="crumbs">
      <li><a href="{% url 'index' %}">首页</a>></li>
      <li><a href="{% url 'users:user_info' %}">个人中心</a>></li>
      <li>我的收藏</li>
    </ul>
  </div>
</section>
{% endblock %}

{% block right_content %}
<div class="right">
      <div class="personal_des Releasecont">
        <div class="head">
          <h1>我的收藏</h1>
        </div>
      </div>
      <div class="personal_des permessage">
        <div class="head">
          <ul class="tab_header messagehead">
            <li><a href="{% url 'users:myfav_org' %}">课程学校</a></li>
            <li class="active"><a href="{% url 'users:myfav_teacher' %}">授课教师 </a></li>
            <li><a href="{% url 'users:myfav_course' %}">公开课程</a></li>
          </ul>
        </div>
        <div class="messagelist">
          {% for teacher in teacher_list %}
          <div class=" butler_list butler-fav-box">
            <dl class="des users">
              <dt>
                <a href="{% url 'org:teacher_detail' teacher.id %}">
                  <img width="100" height="100" src="/static{{ MEDIA_URL }}{{ teacher.image }}"/>
                </a>
              </dt>
              <dd>
                <h1>
                  <a href="{% url 'org:teacher_detail' teacher.id %}">
                    {{ teacher.name }}<span class="key">认证教师</span>
                  </a>
                </h1>
                <ul class="cont clearfix">
                  <li class="time">工作年限：<span>{{ teacher.work_years }}年</span></li>
                  <li class="c7">课程数：<span>{{ teacher.get_course_nums }}</span></li>
                </ul>
                <ul class="cont clearfix">
                  <li class="time">工作公司：<span>{{ teacher.work_company }}</span></li>
                  <li class="c7">公司职位：<span>{{ teacher.work_position }}</span></li>
                </ul>
              </dd>
              <div class="delete jsDeleteFav_teacher" data-favid="{{ teacher.id }}"></div>
            </dl>
          </div>
          {% endfor %}

        </div>
      </div>
    </div>
{% endblock %}